version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase
  ignore:
  - dependency-name: ember-template-lint
    versions:
    - 2.20.0
    - 3.0.0
    - 3.0.1
    - 3.1.1
    - 3.2.0
  - dependency-name: ember-cli
    versions:
    - 3.25.0
    - 3.25.1
    - 3.25.2
    - 3.25.3
    - 3.26.0
  - dependency-name: eslint-config-prettier
    versions:
    - 7.2.0
    - 8.0.0
    - 8.1.0
  - dependency-name: ember-source
    versions:
    - 3.24.1
    - 3.26.0
  - dependency-name: ember-cli-htmlbars
    versions:
    - 5.3.2
    - 5.7.0
  - dependency-name: ember-cli-babel
    versions:
    - 7.25.0
  - dependency-name: eslint-plugin-promise
    versions:
    - 4.3.1
  - dependency-name: eslint-plugin-ember
    versions:
    - 10.1.2
    - 10.2.0
  - dependency-name: focus-trap
    versions:
    - 6.3.0
